CREATE TABLE Publ (
  pubID VARCHAR(129) NOT NULL,
	type VARCHAR(13) NOT NULL,
	title VARCHAR(700) NOT NULL,
	booktitle VARCHAR(132) NOT NULL,
	year VARCHAR(4) NOT NULL,
	publisher VARCHAR(196) NOT NULL
);
ALTER TABLE Publ ADD CONSTRAINT pk_publ PRIMARY KEY (pubID);

CREATE TABLE Auth (
	name VARCHAR(49) NOT NULL,
  pubID VARCHAR(129) NOT NULL
);

-- ALTER TABLE Auth ADD CONSTRAINT u_auth UNIQUE (name, pubID);
ALTER TABLE Auth ADD CONSTRAINT fk_auth_publ FOREIGN KEY (pubID) REFERENCES Publ (pubID) ON DELETE CASCADE;

